### ISSUE TITLE
segfault on player join

### ISSUE THREAD

**Issue by lorpus** [danielga/gm_sourcenet#33]
Ubuntu 19.10 and Ubuntu 16.04.6 latest srcds and latest gmsv_sourcenet_linux build from releases
doesn't seem to occur on 1.1.7

starts happening randomly after some time but i've been able to trigger it like so:

1. lua_run require("sourcenet")
2. join and disconnect
3. changelevel gm_construct
4. join

```Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x224b8800 in ?? ()
[Current thread is 1 (Thread 0xf731d700 (LWP 3048))]
(gdb) bt
#0  0x224b8800 in ?? ()
#1  0xf5cd99a8 in CNetChan::Setup(int, netadr_s*, char const*, INetChannelHandler*, int) () from bin/engine_srv.so
#2  0xf5ce2725 in NET_CreateNetChannel(int, netadr_s*, char const*, INetChannelHandler*, bool, int) () from bin/engine_srv.so
#3  0xf5c46d22 in CBaseServer::ConnectClient(netadr_s&, int, int, int, int, char const*, char const*, char const*, int) () from bin/engine_srv.so
#4  0xf5c469bd in CBaseServer::ProcessConnectionlessPacket(netpacket_s*) () from bin/engine_srv.so
#5  0xf5ce4347 in NET_ProcessSocket(int, IConnectionlessPacketHandler*) () from bin/engine_srv.so
#6  0xf5c4860e in CBaseServer::RunFrame() () from bin/engine_srv.so
#7  0xf5d241ee in SV_Frame(bool) () from bin/engine_srv.so
#8  0xf5ca2c4e in _Host_RunFrame_Server(bool) () from bin/engine_srv.so
#9  0xf5ca35a4 in _Host_RunFrame(float) () from bin/engine_srv.so
#10 0xf5caf628 in CHostState::State_Run(float) () from bin/engine_srv.so
#11 0xf5caf906 in CHostState::FrameUpdate(float) () from bin/engine_srv.so
#12 0xf5caf94d in HostState_Frame(float) () from bin/engine_srv.so
#13 0xf5d38a48 in CEngine::Frame() () from bin/engine_srv.so
#14 0xf5d365f6 in CDedicatedServerAPI::RunFrame() () from bin/engine_srv.so
#15 0xf712cb1a in ?? ()
#16 0xf5d3669d in CModAppSystemGroup::Main() () from bin/engine_srv.so
#17 0xf5d8c2b8 in CAppSystemGroup::Run() () from bin/engine_srv.so
#18 0xf5d369ad in CDedicatedServerAPI::ModInit(ModInfo_t&) () from bin/engine_srv.so
#19 0xf712c7d8 in ?? ()
#20 0xf71855f8 in ?? ()
#21 0xf71855f8 in ?? ()
#22 0xf70db39a in ?? ()
#23 0x08048aab in main ()
```

**Comment by danielga** [comment]
This should be fixed by the most recent builds.
